server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: products
  metrics:
    export:
      prometheus:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true